title: "CS5300 - Database Systems"
description: "Fall 2025 Course Website"
baseurl: "" # Leave empty if deploying to https://username.github.io
url: "https://syeung-cs.github.io" # Replace with your GitHub username
theme: minima
markdown: kramdown
permalink: pretty
