title: "CS1570 - Introduction to C++ Programming"
description: "Fall 2025 Course Website"
baseurl: "" # Leave empty if deploying to https://username.github.io
url: "https://yourusername.github.io" # Replace with your GitHub username
theme: minima
markdown: kramdown
permalink: pretty